### PR TITLE
Adds Paul Blundell as an author & first post

### PR DESCRIPTION
**Pull request by blundell**
what it says on the tin

### CODE REVIEW

**Comment by smhsieh** [comment]
@blundell Thanks for adding - can you add your post first and then I will go ahead and merge your PR

**Comment by blundell** [comment]
ah I was waiting for this to be merged to make a post PR. You want them both in one?

**Comment by blundell** [comment]
Hmm failing on no hero image... I was planning on not having one.

**Comment by blundell** [comment]
> Invalid indentation, you can use tabs or spaces but not both

.... anyone any idea's of how to fix? (automated fix)

**Comment by argyleink** [comment]
most IDE's have a way to fix indentation styles. here it is in sublime

screen shot 2015-09-28 at 11 23 59 am

**Comment by blundell** [comment]
@argyleink thanks! I am using sublime :) done!

**Comment by argyleink** [comment]
yo, just checked this out, ran it locally, and created a PR for you to review. the bummer is, the PR has all of the master updates too, so really you just need to check out your post file. I tabbed it in 1 more time to pacify jade/markdown, then i added some spaces between your ## and header text, and lastly made your ref links bullets. the bullet is optional, but i suggest the other changes. see it all here https://github.com/blundell/androidhub/pull/1

**Comment by argyleink** [comment]
hey look at that, all green =)

**Comment by blundell** [comment]
:100:  nice action, I should stick to java and intellij lol

**Pull request merged**
