### PR TITLE
Fix method name and link for source sample.

### PR DESCRIPTION
**Pull request by nglauber**

### CODE REVIEW

**Comment by smhsieh** [comment]
@nglauber looks like you need to resolve some conflicts to the branch. Let me know if you have questions

**Comment by nglauber** [comment]
It just two small changes... I didn't understand the reason of conflict...

**Comment by argyleink** [comment]
the conflict is with git and merging your code in, git wants your branch to be up to date with the latest from the upstream fork. here's an article to help ya https://help.github.com/articles/syncing-a-fork/

**Comment by nglauber** [comment]
I'm the master of Git...
noidea

**Pull request merged**
